spring.application.name=springboot-internship
spring.datasource.url=jdbc:postgresql://localhost:5433/springboot
spring.datasource.username=postgres
spring.datasource.password=openpgpwd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.web=DEBUG
